### PR TITLE
Fix Delay Attributes

### PR DESCRIPTION
**Pull request by hazukitenki**
I found character delay and line delay aren't been set correctly even if I provided a valid value.
I think the bug is caused by a typo in the getter function, the minimum of `0`, `2_147_483_647`, `data-xxx-delay` is the only param of Math.max.
So I tried to fix the bug by moving the lower bound out of the calling of Math.min and it seems to work now. 
(Please forgive me for my poor English😥)

### CODE REVIEW

**Comment by nholden** [comment]
👋  Hi, @hazukitenki! Thanks for this contribution! ✨ 

Would you mind adding a test for this? I think we'd want one [like this](https://github.com/github/typing-effect-element/blob/5bf0c88dd25e1cceb0c87101688a908f6261ceb7/test/test.js#L71-L77) except where we specify the data attributes when we create the `<typing-effect>` element instead of using the defaults.

**Comment by hazukitenki** [comment]
This is my honor, but I lack the experience of writing tests. 
I wrote this test earlier, but I am not sure if it is sufficient for this situation😖. Do we need more test cases to ensure that the delay attribute is always within the valid range?

**Review by nholden — APPROVED** [review]
This looks perfect to me, thank you! We should be able to get it merged and included in a new release this week.

> Do we need more test cases to ensure that the delay attribute is always within the valid range?

Ideally we'd have some tests for when the data attributes have invalid values, but for the purposes of this PR, the test you wrote is exactly what we needed.

**Comment by hazukitenki** [comment]
You're welcome. I also benefited a lot from it, thank you! 😀

**Pull request merged**
